version: '3.8'

services:
  app:
    container_name: payhere_task_app 	#container 이름 지정
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/payhere?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    depends_on:
      - db

  db:
    container_name: payhere_task_db 	#container 이름 지정
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: payhere
      MYSQL_ROOT_PASSWORD: 1512!@#
      MYSQL_USER: lsm
      MYSQL_PASSWORD: 1512!@#
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
